before:
  hooks:
    - sed -i 's/devel/{{ .Tag }}/' ./pkg/version.json
builds:
- main: .
  binary: catalog-cd
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - s390x
  - "386"
  - mips64le
  - ppc64le
archives:
- name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'


