name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - run: git fetch --prune --unshallow
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: 1.20.x
        cache: true
    - uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --timeout=60m --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
