name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
      with:
        go-version: 1.22.x
        cache: true
    - uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --timeout=60m --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
