name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: 1.20.x
        cache: true
    - uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --timeout=60m --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
